### ISSUE TITLE
[FR] Create Event in Discord for Live Streams

### ISSUE THREAD

**Issue by jazakrzewski** [Blade2021/HIVE#100]
### Is your feature request related to a problem? Please describe.

Use Discord event to show live streams

### Describe the solution you'd like

Either prepopulate a Discord event based on DrZzs stream calendar or create it when he goes live

### Additional context

Seen on Quindors discord but was manually created by an admin

![image](https://user-images.githubusercontent.com/58450237/151616046-f8ad89c0-75ab-4664-a3ce-e97e2e3b0f98.png)

![image](https://user-images.githubusercontent.com/58450237/151616157-c40704cb-d29a-4809-98e2-34c9e6675337.png)

**Comment by SirGoodenough** [comment]
That appears to be the event thing,  interesting...

**Comment by SirGoodenough** [comment]
Of course we would need to know WHEN the stream is supposed to happen for that to work and now we don't have a reliable source for stream time.

**Comment by Blade2021** [comment]
> Of course we would need to know WHEN the stream is supposed to happen for that to work and now we don't have a reliable source for stream time.

I can create an event on the fly.

**Comment by Blade2021** [comment]
When HIVE can handle pulling from google Calendar then yes, that would be the more applicable way to use it but, in the meantime, creating a quick event shouldn't be too hard to do.

**Comment by SirGoodenough** [comment]
The Calendar is updated manually by someone.  Today it said 1:30 but stream was at 11.  That's the source that is the problem

**Comment by Blade2021** [comment]
Maybe Elon Musk can fix that end with his brain chips ;)

**Comment by Blade2021** [comment]
Getting added in 3.5.1
![image](https://user-images.githubusercontent.com/1572869/200459091-1ebece1d-9032-4a4e-af44-c7f7bcdfdfd9.png)
