### ISSUE TITLE
[Bug]  Hive V3 not acting on Restream chat during streams

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#101]
### Describe the bug

During the stream today ~ask would not work

### How do you reproduce the bug?

1]  ~ask from from Twitch or YT
2] Also Links did not work from Twitch or YT.
3] Right at end of stream I tried a link from discord and it worked.

### Expected behavior

~ask and links from Restream chat should trigger HIVE during a stream and do not appear to be doing so.

### Screenshots

Todays livestream chat, Mt screenshot is not working.

**Comment by Blade2021** [comment]
I'm pushing a minor update tonight.  We'll see if it'll fix it during the next stream.  Hopefully he streams on a weekend or later in the day if on a week day next time.

**Comment by Blade2021** [comment]
Verified and Fixed.
