### ISSUE TITLE
[Bug] Karma does not appear to be added with HIVE v3

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#102]
### Describe the bug

After waiting 25 hours and giving away no karma, my total stayed at 5.
Justin Z's count stayed at 0.

### How do you reproduce the bug?

I monitored over 24 hours and saw no karma added.

### Expected behavior

1 point be added per day, as stated with ~getkarma command

### Screenshots
![Screenshot_2022-01-30_19-14-00](https://user-images.githubusercontent.com/47349533/151727543-d9bc1589-3ec2-412e-aefa-5351244c19b5.png)
![Screenshot_2022-01-30_19-15-02](https://user-images.githubusercontent.com/47349533/151727542-a023a4b6-70a7-495f-bae4-3d14e8f26544.png)

**Comment by Blade2021** [comment]
I found the bug.  Will fix later.

**Comment by Blade2021** [comment]
Fixed?
