### ISSUE TITLE
[Bug] Activity stuck at item #22

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#103]
### Describe the bug

I noticed Activity is not rotating.  the last time I saw it changed was during a stream changing into and out of stream mode.

### How do you reproduce the bug?

N/A

### Expected behavior

Rotation of listed activities until streammode true, then locked to streammode until that is released and rotation resumes.

### Screenshots

![Screenshot_2022-02-12_12-20-29](https://user-images.githubusercontent.com/47349533/153723631-986e9251-4a23-4cdf-91f3-81e69f559395.png)

### Additional context

What I if told you
You read the first line wrong?

**Comment by Blade2021** [comment]
Fixed for now.
