### ISSUE TITLE
[Bug] LED Power Calculation Commands not working

### ISSUE THREAD

**Issue by jazakzewski** [Blade2021/HIVE#104]
### Describe the bug

LED power usage calculations are returning ERROR: Bad format received

### How do you reproduce the bug?

Executed any of the led commands

### Expected behavior

Power calculation responses provided

### Screenshots

![image](https://user-images.githubusercontent.com/58450237/154479830-1ae6d439-bcb2-44a2-9d19-ee4908353d5b.png)

**Comment by Blade2021** [comment]
Fixed.
