### ISSUE TITLE
[Bug] Giving Self Karma Doesn't Potato

### ISSUE THREAD

**Issue by jazakrzewski** [Blade2021/HIVE#106]
### Describe the bug

When trying to do the Karma reaction on your own message in a normal channel, it is removed but no potato reaction from Hive
When trying to do it in a thread the reaction stays but seems it does not count for anything

### How do you reproduce the bug?

React to own message with Karma emoji

### Expected behavior

Reaction removed and potato response from Hive

**Comment by Blade2021** [comment]
Fixed.
