### ISSUE TITLE
[Bug] Ask Module not working properly

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#107]
### Describe the bug

~ask is not triggering from any platform

### How do you reproduce the bug?

Tested from Discord, Twitch, and YT.
Stream mode is on.
I turned stream mode off and back on, and the Discord Ask then worked, not the others...

### Expected behavior

~ask shows in the #live-stream and Hive does magic to push question to #live-questions channel

**Comment by Blade2021** [comment]
Fixed.
