### ISSUE TITLE
[Bug] Extra comma comes along with live-stream-links during streams

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#111]
### Describe the bug

The URL that is pulled from chat during Live streams when someone types in a URL shows up in the live-stream-links channel with an extra leading comma.

### How do you reproduce the bug?

Happens during live-streams

### Expected behavior

no comma

### Screenshots

![Screenshot_2022-08-07_11-30-29](https://user-images.githubusercontent.com/47349533/183301170-415143e0-6e04-4b31-83b7-91b3cba3f00e.png)

### Additional context

Nothing is 'broken', but it makes it fiddly to copy the links out for other uses.

**Comment by Blade2021** [comment]
Fixed in v3.5.1
