### ISSUE TITLE
[FR]  Idea for ~ph

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#119]
### Is your feature request related to a problem? Please describe.

Newbies often are intimidated with Discord.

### Describe the solution you'd like

When ~ph is invoked, instead of responding with 'Go the led-lighting-diy', it says Your Question would be better answered in this other channel.
Then Hive pages them in the LED channel with a short message.

Note, if the original hive message is set to time out, be sure to add an emoji to the users message to show that it was responded to, or else multiple people will tell the questioner where to go.

**Comment by Blade2021** [comment]
While this wouldn't be overly complicated, I think the concept is over-engineered.  The point of the PH reference is to teach them where to go and how to go there.  If we just tag them they might get the wrong idea.  

I'm not going to lie.  I'm very selfish with rate limiting.  To respond in the original channel, then to respond in the LED channel would require a minimum of 2 events/requests.  Removing the original message, a third request, and then adding an emoji, a forth event.

So while I appreciate the feedback/request.  I have to decline.
