### ISSUE TITLE
References list

### ISSUE THREAD

**Issue by cischology** [Blade2021/HIVE#20]
I would like to have the ability when a user triggers the bot for an acronym i.e ~Tuya or ~Tasmoto or ~flash , the bot will DM that user with a brief description , links and or how-to. if acronym doesn't exist , maybe DM an admin or mod and ask them to update bot database with that info and at the same time DM the user the acyrnom is not available and to check back later.

**Comment by Blade2021** [comment]
From the way it sounds this is something that can be easily implemented.

**Comment by Blade2021** [comment]
The list is growing as each day passes but the structure is there.  For now any requests for references should be submitted here: https://github.com/Blade2021/HIVE-RefData

**Comment by SirGoodenough** [comment]
Request a modification to this feature:
Have the regular response to reference request be a DM back to the user, but make a -show flag available to just staff that will display the reference in the chat for helping a user understand an issue. -show be only available to bannerman up in rank to limit channel traffic.
