### ISSUE TITLE
Direct Messages

### ISSUE THREAD

**Issue by ikifar2012** [Blade2021/HIVE#25]
Allow people to direct message commands to the bot

**Comment by ikifar2012** [comment]
I was going to say the basics like ~help

**Comment by Blade2021** [comment]
I have the info command set for private messages in my next upload however its one of the few I can do due to many of the others have to check for access.  Including the ~help command.

**Comment by Blade2021** [comment]
This is now implemented for all reference triggers, info command, and reference list.  

Everything else must stay on guild only.  (at least for now)
