### ISSUE TITLE
Discord incentive to stay active as leaders in the community

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#27]
Sir_GoodenoughToday at 12:16 PM
Hey Doc, Violent Poo, Blade and I were chatting.  What do you think about keeping the Radiant/Yeoman/Bannerman groups current with an incentive to stay up to date and active in the community.  We were thinking if they have not been in on your discord people chatting for some time period, say 30 or 60 days, they would be bumped down a level.  The thought is to make sure that people who can break things stay current with the going's on of the server and they won't break something inadvertently when they come back.(edited)
[12:17 PM]
Blade says that Hive could do this for us.  we won't go anywhere, though, without your OK for this.(edited)

DrzzsToday at 12:17 PM
hmmm
[12:18 PM]
by mess something up do you mean like bot commands?

Sir_GoodenoughToday at 12:18 PM
Getting back up would be manual your ok(edited)
[12:19 PM]
I'm mostly concerned about radiants and Discord channel changes, etc(edited)
[12:19 PM]
Changing access to YT and the Bots are out of Hive's scope, it would be Discord roles(edited)
[12:20 PM]
Poo thought they should also stay active to keep other roles.

DrzzsToday at 12:21 PM
I'd like to have some level of honorary roles.  That's kinda what I intended with the Yeoman and Bannermen. I don't care if we change the privileges of some roles.

Sir_GoodenoughToday at 12:22 PM
This came up because someone we didn't know Fubar20, showed up with a link today, and he/she is a radiant that's had 3 posts to your server in a year.   Looked like a security issue to me.

DrzzsToday at 12:22 PM
haha
[12:22 PM]
I don't even know who that is.

Sir_GoodenoughToday at 12:22 PM
see...

DrzzsToday at 12:22 PM
ok, sounds necessary

Sir_GoodenoughToday at 12:23 PM
We could do an emeritus role that collects them before general, but has general permissions

DrzzsToday at 12:23 PM
make it so #1
[12:24 PM]
ooh, I like that

Sir_GoodenoughToday at 12:24 PM
OK, I'l put in a request to hive.

DrzzsToday at 12:24 PM
thanks

**Comment by Blade2021** [comment]
Task: Remove users from privileged roles after a set time period. 
Method: 
- [ ] Scan users once per day for additions/modifications/deletions from roles.
- [ ] Pull status online event and match to a user with privileged access
- [ ] Update a DB of current date
- [ ] Scan once per day of users that have past the inactive time.
- [ ] Remove users from roles and place into inactive role

**Comment by SirGoodenough** [comment]
So you are thinking of checking when they started a role and when they last were active in the channel, or just activity on the channel?  IE: Should the tree look like Radiant not active for time becomes Bannerman, Bannerman not active becomes Yeoman, Yeoman not active becomes Emeritus (honorary), or Radiant or Bannerman or Yeoman not active becomes Emeritus immediately?  
You would not have to check Emeritus at all.  It would be same permissions as general.

**Comment by Blade2021** [comment]
My plan is to just put them in a inactive role, no matter what ranking.

**Comment by SirGoodenough** [comment]
And inactive will be same as general permissions, just a different color/name.  I think that's what the doc wanted kind of thing based on the conversation.

**Comment by Blade2021** [comment]
Indeed.

**Comment by ViolentPoo** [comment]
I would suggest that it also makes a log entry stating the rank of the user before reassigning them.

**Comment by Blade2021** [comment]
![image](https://user-images.githubusercontent.com/1572869/83320894-7b048f80-a219-11ea-8d82-e90e7fb8664e.png)

**Comment by Blade2021** [comment]
Made a HUGE amount of progress today on this.  The database is fully functional, Just gotta start recording Dates and get the check functions in place then we will be cooking with fire :D

**Comment by Blade2021** [comment]
Done.
