### ISSUE TITLE
Database Integration

### ISSUE THREAD

**Issue by Blade2021** [Blade2021/HIVE#3]
HIVE needs to be able to query and assign values to a database for future references.

**Comment by SirGoodenough** [comment]
Request a modification to this feature:
Have the regular response to  reference request be a DM back to the user, but make a -show flag available to just staff that will display the reference in the chat for helping a user understand an issue.  -show be only available to bannerman up in rank to limit channel traffic.

**Comment by Blade2021** [comment]
> Request a modification to this feature:
> Have the regular response to reference request be a DM back to the user, but make a -show flag available to just staff that will display the reference in the chat for helping a user understand an issue. -show be only available to bannerman up in rank to limit channel traffic.

I think you mean #20

**Comment by SirGoodenough** [comment]
maybe....

**Comment by Blade2021** [comment]
Database implementation is done.
