### ISSUE TITLE
Suggestion Pool

### ISSUE THREAD

**Issue by Blade2021** [Blade2021/HIVE#38]
Suggestion Pool
 
Forward suggestions into a voting application AFTER approval from a mod/admin.  When the suggestion is submitted it will receive an unique ID that will be written to a row in the DB.  This ID will keep track of the status of the suggestion and the message ID of the poll after approval. 

Status Codes:
Submitted
Approved, Poll Created, Voting started
Request Approved
Request Declined
Rejected, No Poll
 
MessageID will be used to submit an approval/reject message into the embed.
 
When a user wants to make a request, said user will just have to do !suggest or !suggestion then said user should receive a direct message to fulfill the request with the same method as localpoll.
 
Applicable commands:

- [ ] Suggest - Initialize a suggestion (Everyone)
- [ ] SuggestionPool - Get a list of all suggestions that are awaiting approval. (Staff)
- [ ] SuggestionApprove - Approve a suggestion for it to be created into a poll (Staff)
- [ ] SuggestionReject - Reject a suggestion. (Staff)
- [ ] SuggestionMessage - Get the status message of a suggestion (Staff)
- [ ] SuggestionSetMessage - Set a status message on the suggestion (Admin)
- [ ] SuggestionList - Get a list of currently open suggestions (Staff)
- [ ] SuggestionListAll - Get a list of ALL suggestions (Open & Closed) (Admin)
- [ ] SuggestionsStatus - Get the status of a suggestion via ID (Everyone)
- [ ] SuggestionByAuthor - Get a list of all suggestions by a certain author via ID or mention. (Staff)
- [ ] SuggestionSCode - Set the status code of a certain suggestion. (Admin)
- [ ] SuggestionInfo - Get all info about a suggestion in a nice format.  (Suggestion description, author, status code) (Staff)
- [ ] SuggestionPurge - Purge all related information and messages to a certain suggestion.  This command should remove the table's row, the original message if applicable, as well as any posted poll messages.

 
Possibly query the votes automatically after a poll has been open for x amount of days.  This method won't automatically approve or deny the request but send a total votes. 
 
Submission message:
Hi @USER, Thanks for submitting your suggestion.  After your suggestion has been reviewed, it will be created into a poll in the #suggestions channel.  Your suggestion ID is #0045

**Comment by Blade2021** [comment]
- [ ] Need to add the ability for reactionListener to remove reactions that are not a part of the poll.

**Comment by SirGoodenough** [comment]
Enhancement Idea:   In order to know when the vote count can be considered statistically significant, we should have HIVE calculate the percentage of votes against active user count or the percentage of people that have read the message against active user count if that is possible, and report this to aid in the decision to call the voting done or not.
We don't know if we have a valid number of users that have seen the idea (or voted) to know if we can call the vote or not.  This is better than a timed response and if we can get the number of people that have read the message, better than number of votes.

**Comment by Blade2021** [comment]
Stale.
