### ISSUE TITLE
Channel Cool-down - lock

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#41]
**Is your feature request related to a problem? Please describe.**
sometimes discussions on a channel can become heated and not karma++ friendly.  Admins should have a way to cool off the discussion.

**Describe the solution you'd like**
My suggestion would be lock the channel with a warning message like~  
```bad activity, be nice, if this continues on another channel you risk a server ban...  ```
Leave that up for an hour then pull the message and release the channel...  That way it blames everyone because it is always a clash with more than 1 person involved.  If someone does something bad or continues on another channel we just bounce them manually.  That's my input, anyway....

**Who will have access to this feature?**
Admins

**How will this help improve HIVE?**
This will help improve HIVE by allowing for a cool down time and hopefully prevent people that are 'in the moment' from being banned.

**Additional context**
See log from 15-july-2020....
May cause a problem on live-stream if accidentally triggered during a stream, May want to prevent it from running when stream-mode is enabled.

**Comment by Blade2021** [comment]
Implemented in 0.17.7
