### ISSUE TITLE
Trigger Hive to Send a Reference to a User's DM.

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#46]
**Is your feature request related to a problem? Please describe.**
It is often challenging to get a new user to trigger a reference so they can read it off channel, and to -show the reference for a conversation between just 2 people in a channel is not desirable.

**Describe the solution you'd like**
I would like the ability for 'Staff' to do a command similar .hainstall -push @Blade2021 .  This would in my mind push the reference to the user in a DM but it comes from Hive and stays out of the channel.

**Who will have access to this feature?**
Staff

**How will this help improve HIVE?**
I do not necessarily want to start a DM stream with everyone I am helping, and the references are not available in the world of the DM's.  This will allow me to help people without channel 'reference walls' when it is a one on one.

**Additional context**

**Comment by Blade2021** [comment]
I will work on this after restructuring the reference system.

**Comment by SirGoodenough** [comment]
Hmmm....
 @Blade2021  Have to be careful with that one.  It is a grey area for violating Discord TOS
BoTs aren't suppose to send DMs without consent.

So what is consent?  Opt-in?  What about it says this reference link is sent to you from Sir_Goodenough?

I also realize you would need characters, so the character limit would have to be lowered so it could work and the existing ones trimmed a bit.

**Comment by Blade2021** [comment]
Yep, as said in discord,  I have to be careful with scenarios like this.  Sending a user a message without consent or opting in,  in the form of triggering a command can be viewed as spam.  At this time,  I feel it would be best to not pursue this.
