### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by ikifar2012** [Blade2021/HIVE#47]
**Is your feature request related to a problem? Please describe.**
I think it would make it easier to deploy the bot if you made a docker image for HIVE, you can make a different tag for each version so it is easy to rollback in the event of an issue and you can have the docker image created automatically when you push to the main branch of your git repo

**How will this help improve HIVE?**
This will allow easier deployment for you 

**Additional context**
I am willing to help create the docker image if I know what you need from it

**Comment by Blade2021** [comment]
For HIVE, this isn't really something that would be much of an improvement for me.  We are using a DB, so I'd have to worry about transferring data to the new images, as well as setting up parameters each time.  With the current setup, I compile the code and run.  Old versions are still kept for backup purposes.

I appreciate the offer but think i'll have to pass on this one.
