### ISSUE TITLE
Hive not giving out the correct points to Staff.

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#49]
**Describe the bug**
Hive is doing 1 for everyone, including staff.  It was originally giving more to staff per day.
**To Reproduce**
~getpoints
go for a full day without giving any karma
~getpoints

**Expected behavior**
The difference should be nor that +1
**Screenshots**
na
**Additional context**
We tlked about it in person also.

**Comment by Blade2021** [comment]
Old BR.  Closing for now.
