### ISSUE TITLE
Cleanse just before stream marker start.

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#52]
**Is your feature request related to a problem? Please describe.**
We are manually having to cleanse the live chat and the live ask channels before the stream starts.  We usually remember, sometimes don't.  Sometimes the boss drops an unexpected stream on us.  As this is currently hard coded within HIVE, I would like to be able to cleanse these 2 channels (and not the links channel) before the stream start marker is dropped in.

**Describe the solution you'd like**
code in the cleanse routing in the live chat and the live ask channels before the stream marker is dropped and restream is accepted.

**Who will have access to this feature?**
Hard configured, IE programmer.

**How will this help improve HIVE?**
Old chat and old ask content is deemed expired when the next stream starts.  He never answers old questions, and the old chat is available in the YT stream if someone wants to see it.  We would not have to be manually remembering to clear stuff out on time, and the content would be available until the last minute IF anyone should want to refer back to it.   (I do occasionally)

**Additional context**

**Comment by Blade2021** [comment]
Not really feasible as the bot would be deleting messages as people started chatting in the new stream.  

Might be able to trigger it 24hours after a stream has started.

**Comment by SirGoodenough** [comment]
I thought about that, the first 5 minutes after he hits the button is the lead credits rolling and people saying first and hello.  No loss if it is lost.. No real 'content' anyway.
 (Unless it messes with Hive as it's deleting)
As he gets into the 12 streams of Christmas, there likely will be one every day.  Possibly within 24 hours...
Can you capture the scheduled stream time and do an hour before that?

**Comment by Blade2021** [comment]
> Can you capture the scheduled stream time and do an hour before that?
Not really without an intense amount of integration.  Might come back to this at some point but no time soon.  Closing for now.
