### ISSUE TITLE
Use Karma to add helper role.

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#54]
**Is your feature request related to a problem? Please describe.**
There has been a slight vacuum on what karma is for besides bragging rights.

**Describe the solution you'd like**
First step, limit the number of Karma that someone can get in a day to prevent cheating for step 2.
Step 2, use the number of karma points total to move people from bannerman to yeoman to radiant.  If they not already staff, the upgrade doesn't work.  If they are already staff, karma is somewhat = to experience and/or peer approval, and should be encouraged and rewarded.  If Doc wants to upgrade someone for his own reason, that's still available.  The tool will look at the current roles and add the appropriate one bases on the current ones.
For example (values are an example), they get 100 karma, they move from bannerman to yeoman.  If they get 400 karma, they move from yeoman to radiant.

**Who will have access to this feature?**
Admins, Staff.

**How will this help improve HIVE?**
encourage helping others.

**Additional context**

**Comment by Blade2021** [comment]
I don't think its truly fair to add/remove staff based on Karma.  Sure it helps as an analytical tool, but otherwise isn't really used enough for this purpose.  I do have plans to do a "helper" role eventually that'll get incorporated but the helper role will not have mod permissions.

**Comment by Blade2021** [comment]
Stalemate.  We will have karma roles for top 3 per week handed out.
