### ISSUE TITLE
[FR] Additional text for the justask 

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#59]
**Is your feature request related to a problem? Please describe.**
Skipping thru another forum, found this quote.  Thought it would be a great addition to ~justask

**Describe the solution you'd like**
```
Quality of answers is related to the quality of questions. Good questions will get good answers. Useless answers are a sign of a poor question.
```

**Who will have access to this feature?**
all

**How will this help improve HIVE?**
This will help improve HIVE by driving better answers for questions and questions for answers.

**Additional context**
Found at the end of this post...
[Arduino.cc link about coupling caps](https://forum.arduino.cc/index.php?topic=613477.0)

**Comment by Blade2021** [comment]
I think its best to keep it simple at the moment.
