### ISSUE TITLE
Emote Command Acting Odd

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#64]
**Describe the bug**
In updating the rules, Emote command carries too many characters into the new message.

**To Reproduce**
1. When I type:
```
~Embed update -m 801653299517849601 **THE RULES**

**1.** Be respectful. Ha ....etc
```
2. HIVE puts this into the message:  
```
te -m 801653299517849601 THE RULES

1. Be respectful. Ha ....etc
```

**Expected behavior**
This should not be there:
```te -m 801653299517849601 ```

**Screenshots**
![Screenshot at 2021-02-03 02-00-22](https://user-images.githubusercontent.com/47349533/106716859-8f790300-65c4-11eb-912f-8fdf6f8f8b29.png)
.

**Additional context**

**Comment by Blade2021** [comment]
Did you add the approved tag or was that a part of the template?

**Comment by Blade2021** [comment]
![image](https://user-images.githubusercontent.com/1572869/106818733-b1b36500-6646-11eb-9303-bcbe855340e3.png)
