### ISSUE TITLE
Karma Diamond Assignment Error at 40

### ISSUE THREAD

**Issue by jazakzewski** [Blade2021/HIVE#65]
**Describe the bug**
At 40 the :small_blue_diamond: is removed automatically but :diamond_shape_with_a_dot_inside:  isn't added automatically till 41 but is available to the user

**To Reproduce**
Saw this happen with both evilwoodstock and kklown, in both cases giving them karma to get to 41 added the :diamond_shape_with_a_dot_inside: right away

**Expected behavior**
:diamond_shape_with_a_dot_inside:  is added automatically at 40

**Screenshots**

**Additional context**

**Comment by jazakzewski** [comment]
@Blade2021 Same issue exists at level 60

**Comment by Blade2021** [comment]
Being removed in v3.  Closing.
