### ISSUE TITLE
[FR] Assignable Roles

### ISSUE THREAD

**Issue by SmAsH-jl** [Blade2021/HIVE#66]
**Is your feature request related to a problem? Please describe.**

Just a feature. 

**Describe the solution you'd like**

build in a system to allow roles below current staff/mod level to assign role levels below them. 

**Who will have access to this feature?**

dmins, Staff,

**How will this help improve HIVE?**

This will help improve HIVE by driving more people crazy. <--- this

naw really just to add more functionality. 

**Additional context**

**Comment by SirGoodenough** [comment]
Just a side comment, this is what Discord does now if allowed in the permission stack.

**Comment by Blade2021** [comment]
> Just a side comment, this is what Discord does now if allowed in the permission stack.

Very good point.
