### ISSUE TITLE
Initial 5 Points not given

### ISSUE THREAD

**Issue by jazakzewski** [Blade2021/HIVE#67]
**Describe the bug**

New user joins and isn't give the initial 5 points

**To Reproduce**
1. When I type '...'
2. The bot does this '....'

New user joins and using the command ~getpoints to find they have 0 points

**Expected behavior**

Initial 5 points should be assigned

**Screenshots**

![image](https://user-images.githubusercontent.com/58450237/107149584-6390b100-6927-11eb-816f-925c755f34c0.png)

**Additional context**

**Comment by Blade2021** [comment]
Investigating...

Fake account did start with 0 points instead of 5.

**Comment by Blade2021** [comment]
Fixed for now.

I think the point override was removed from HIVE and scheduled to be put into the database as a default value but that never happened.
