### ISSUE TITLE
[FR] Welcome Banner Suggestion

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#68]
**Is your feature request related to a problem? Please describe.**
People may not know how to change their avatar when new to the guild.

**Describe the solution you'd like**
You have a nice message to encourage people to use a custom avatar, so we should add a statement on how to do that.  A link or better yet a suggestion to use the ~avatar reference.

**Who will have access to this feature?**
People being welcomed that are still using clyde.

**How will this help improve HIVE?**
This will help improve HIVE by driving more people crazy. :heavy_check_mark: 

**Additional context**
N/A

**Comment by Blade2021** [comment]
This has been completed.
