### ISSUE TITLE
[FR] Add Switch for Reference commands

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#69]
**Is your feature request related to a problem? Please describe.**
Some references, especially ~reflist, would be handy to have at hand as opposed to calling it in the middle of a conversation.

**Describe the solution you'd like**
Add an optional modifier to at least ~reflist, if not all reference requests, to have HIVE send the output to the requester's DM instead of to the Chat.

**Who will have access to this feature?**
anyone able to call a reference.

**How will this help improve HIVE?**
make chats flow better without a long list of references showing up in the chat.

**Additional context**
Rule 34...   RE: the issue number.

**Comment by Blade2021** [comment]
My policy for DM's from the BOT requires the user to "request" the DM.  

By allowing staff to push the BOT to message a user could be considered as a method of spam.
