### ISSUE TITLE
Extended References missing stuff.

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#70]
**Describe the bug**
Extended References appear to be missing inks and Installation instructions.  

**To Reproduce**
Call an extended reference.
Missing these sections.
Descriptions appear to be fine.  IE extended References are looking like References.

**Expected behavior**
See Links and Installation section.

**Screenshots**
n-a

**Additional context**
n-a

**Comment by Blade2021** [comment]
Extended References are being phased out as they add complications.
