### ISSUE TITLE
[FR] Ability to add Public Thread ability by role

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#72]
**Is your feature request related to a problem? Please describe.**
The new Private Thread Ability would be a good perk for people that contribute as opposed to everyone.

**Describe the solution you'd like**
Be able to allow certain Roles, thinking the level higher than the minimum heimdal role to allow people who are active at some minimum level access to public threads.

**Who will have access to this feature?**
Chatterbox & higher in the heimdal list

**How will this help improve HIVE?**
Discourage lurkers if they want to use Threads

**Additional context**
https://discordapp.com/channels/469330414121517056/469914813540204545/869987087166869526

**Comment by Blade2021** [comment]
Private thread require Discord Perk Level 2 or higher.  

The library we use also doesn't currently support thread operations.  I will plan to revisit this request at a later date.

**Comment by Blade2021** [comment]
#72
