### ISSUE TITLE
[FR]  Add Role filter for Private Threads

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#73]
**Is your feature request related to a problem? Please describe.**
Private Threads would be a great perk for contributors to the channel

**Describe the solution you'd like**
Add the ability to allow certain roles to access Private Threads, thinking Twitcher and higher, but the exact level is up for debate.

**Who will have access to this feature?**
Twitcher or higher?  Get a consensis...

**How will this help improve HIVE?**
This will help improve HIVE by driving more people crazy.

**Additional context**
https://discordapp.com/channels/469330414121517056/469914813540204545/869987087166869526

**Comment by Blade2021** [comment]
Private Threads require Discord Perk Level 2 or higher.

The bot library also doesn't support thread operations at this time.  Revisiting at a later date.

**Comment by Blade2021** [comment]
#72
