### ISSUE TITLE
[FR] Add Mod command to send all references to a channel in Discord.

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#76]
**Is your feature request related to a problem? Please describe.**
On a regular basis, plus when several additions are added to the reference list, I have a need to trigger all the references to test function and test the contained links.

**Describe the solution you'd like**
I would like to see a moderator command that will trigger all the references that are on the reference list in alpha order, sending them to the current channel.

**Who will have access to this feature?**
Admins

**How will this help improve HIVE?**
The current method is to type them all in one by one, and it is very annoying.  Using this command, They would be triggered then I can just go back and test the links and check the spelling and formatting.

**Additional context**

**Comment by Blade2021** [comment]
Not sure how I feel about this one.

The bot has rate limits that can't be exceeded.  By posting (50+) messages back to back, that rate limit will be hit fairly quickly.

**Comment by SirGoodenough** [comment]
How do you handle the cleanse command?
Also, is it better if sent to a DM?

**Comment by Blade2021** [comment]
> How do you handle the cleanse command?
> Also, is it better if sent to a DM?

Cleanse hits the rate limit as well.  But that one is handled a bit different since its removing messages instead of sending them.

DM would be the same issue.  Sending that # of messages that quickly could be considered spamming.

**Comment by SirGoodenough** [comment]
aaahhh

**Comment by SirGoodenough** [comment]
drop one every minute or something...

**Comment by Blade2021** [comment]
I don't think this is an immediate need.  I would have to suggest to remain sending the commands for any updated referencing manually.
