### ISSUE TITLE
[FR] Move ~led output to #bot-spam

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#80]
**Is your feature request related to a problem? Please describe.**
The new ~led command is popular, but drops a lot of spam on channels.

**Describe the solution you'd like**
Would like to see HIVE respond in the local channel where the BOT command is entered with a statement like 'Look in #bot-spam for Response', then drop the response in the #bot-spam channel tagging the requestor.

**Who will have access to this feature?**
Admins, Staff, Members?
all

**Additional context**

**Comment by Blade2021** [comment]
This has calmed down since the stream.  I think it is better to leave it up to the staff to communicate where they should use bot commands at this time.
