### ISSUE TITLE
[FR] Stream Economy/Point system

### ISSUE THREAD

**Issue by Blade2021** [Blade2021/HIVE#84]
**Is your feature request related to a problem? Please describe.**
No problem.  Only solutions.

**Describe the solution you'd like**
It would be nice to have a system that allows everyone to gather points from several options:
- Being active on discord (Reading)
- Posting on discord (Writing)
- Receiving karma for helping
- Saying "here" during a live stream?

HIVE would then track this data using a database and users would build a bank of points.  During a livestream, said user could "spend" the points on turning on lights or displaying a message on the stream, or other fun tasks.

**Who will have access to this feature?**
The world.

**Additional context**
Nope.

**Comment by Blade2021** [comment]
Need ability for senior staff to manage webhooks.

**Comment by Blade2021** [comment]
https://dev.streamlabs.com/docs/triggering-alerts

**Comment by SirGoodenough** [comment]
First on a live stream is always a contest if it has points or not, so why not reward it?

**Comment by Blade2021** [comment]
That's a good idea!  I'll have HIVE make an announcement in the live stream channel and then it'll be whoever claims first there.

**Comment by SirGoodenough** [comment]
Doesn't Heimdal already count their posts , compare that to the welcome date...   OR only count first post if it happens within say 2 hours of the welcome post, and the responder has to do a reply, . just throwing things out there.

**Comment by Blade2021** [comment]
> Doesn't Heimdal already count their posts , compare that to the welcome date...   OR only count first post if it happens within say 2 hours of the welcome post, and the responder has to do a reply, . just throwing things out there.
> 

It does but it's on a whole different server with a different database.

**Comment by SirGoodenough** [comment]
I know, 3 laws, but maybe they can text each other.

**Comment by Blade2021** [comment]
> I know, 3 laws, but maybe they can text each other.

With the next Sherlock update.  I should be dropping about 40% of my current ram usage.  That might give me enough space to run Heimdall on that server as well.  If thats the case then the "first post / first reply" might be more feasible.

**Comment by Blade2021** [comment]
![image](https://user-images.githubusercontent.com/1572869/148878786-037b5baf-b374-49e7-8f1a-c996b38cda4c.png)

**Comment by Blade2021** [comment]
ToDo:

- [ ] Add queue handler for accepting requests (FIFO)
- [ ] Setup StreamLabs API Request Template
- [ ] Setup First /Here gets bonus points

**Comment by Blade2021** [comment]
Added in 3.5.1
