### ISSUE TITLE
[FR] Slash Commands

### ISSUE THREAD

**Issue by Blade2021** [Blade2021/HIVE#87]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Enable some of the current commands to be used as a "slash" command.

**Who will have access to this feature?**
All, Staff

**Additional context**
Command List:

- [x] Commands
- [x] GetKarma
- [x] GetPoints
- [x] LED
- [x] LED List
- [x] Who
- [x] Help

Staff ONLY!
- [x] Activity
- [x] ~~Cleanse~~
- [x] ~~Clear~~
- [x] ~~Reload~~
- [x] StreamMode
- [x] Embed

**Comment by SirGoodenough** [comment]
Cleanse is scary, we need to talk to every one that has it what it's for so they don't wipe a channel somewhere.

**Comment by SirGoodenough** [comment]
I request that a confirmation parameter, like a boolean true, be added to the /cleanse command before it becomes a slash command.
Worried about accidentally typing '/ c enter' and it activates in the wrong place.
requiring a true / false makes it much safer.

**Comment by Blade2021** [comment]
Wrapped up in v3.5.1
