### ISSUE TITLE
[FR] Automatic DePin Messages

### ISSUE THREAD

**Issue by Blade2021** [Blade2021/HIVE#88]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Automatic Pin/DePin for Messages.

Have HIVE automatically unpin things after x amount of time.

**Who will have access to this feature?**
Staff Only

**Additional context**

**Comment by SirGoodenough** [comment]
Add set time limit to this.  Some things are longer term.

**Comment by Blade2021** [comment]
> Add set time limit to this. Some things are longer term.
That was already in the plan.  Its also not meant for all pins, just a function for us to set temporary pins.

**Comment by Blade2021** [comment]
Closing this Issue as this feature has been fully integrated.
