### ISSUE TITLE
[FR]  Keyword response that Mods can set

### ISSUE THREAD

**Issue by SirGoodenough** [Blade2021/HIVE#94]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when 

No Problem, just a fun thing.  There are currently filters for words such as karma, etc that trigger responses specifically coded.  How about a Mod set general one to cover them all?  One set of coding, multiple uses.

**Describe the solution you'd like**

So something that a Mod can set-up.  Parameters for: 
> trigger word
> messages before it repeats/triggers again
> excluded channels (don't want the NodeRed channel triggering on NodeRed, for instance)
> what the response is

I specifically was thinking about adding karma and Node Red as triggers, but there's always something.  Bonus if you can add multiple trigger words for same response, and if you can use phrases like 'node red' .

**Who will have access to this feature?**
Admins, Staff, Members?

Set up by admins and triggered by all

**Additional context**
![easy-e1628794956389](https://user-images.githubusercontent.com/47349533/148657425-1462036f-6a36-4fd4-b0ce-a4ff03d571d4.png)

**Comment by Blade2021** [comment]
so....

References?

**Comment by SirGoodenough** [comment]
Yes we can drop references if we are there, but thinking auto.

Or are you thinking we pick a reference to drop on an auto keyword scheduler like that?

That works for me.

**Comment by Blade2021** [comment]
Just trying to decipher what your intentions were. 

You want a trigger word without the bot prefix to trigger the post?

**Comment by SirGoodenough** [comment]
So now karma or thanks or whatever is mentioned, HIVE drops a post.
Instead of ones you have to code every time like that, have one that is a mod command and we can add it.  If the response is pick a reference to reply with, that works.

**Comment by Blade2021** [comment]
I've thought about it for a while and I honestly can't jump on board with it.  It has a high risk for spam, could get VERY annoying even if the trigger limit is set for once ever hour, seeing the same message posted day after day gets very annoying.  That's another reason for the thanks trigger switching to the package method.

Sorry bud,  Gotta say no to this one.

**Comment by SirGoodenough** [comment]
Not a problem.
I kind of agree but it would have been cool.
Ideas are free, and worth every cent.  I have plenty more!
